"""Portable regression inputs; actual code tests are not simulation evidence.

All generated user/task/measurement scenarios remain synthetic. The parser
receipt is generated by executing the packaged tests, independent diagnostic
probes, and two source-preserved native-format excerpts. No Aspen is opened.
Optional private regressions require an explicit external profile with hashes.
"""
from __future__ import annotations
import argparse
import hashlib
import importlib.util
import io
import json
from pathlib import Path
import sys
import tempfile
import unittest

SKILLS = Path(__file__).resolve().parents[3]
OPTIONS = None
RECEIPT = None


def reference(path):
    path = Path(path).resolve()
    return {'path': str(path), 'sha256': hashlib.sha256(path.read_bytes()).hexdigest().upper()}


def case_directory_name(test_name):
    """Stable short artifact identity avoids Windows legacy path-length limits."""
    return 'case_' + hashlib.sha256(test_name.encode('utf-8')).hexdigest()[:12]


def configure_test_arguments(prefix='chemical-skill-regression-'):
    global OPTIONS
    if OPTIONS is None:
        parser = argparse.ArgumentParser(add_help=False)
        parser.add_argument('--artifact-root', type=Path)
        parser.add_argument('--external-evidence-profile', type=Path)
        OPTIONS, remaining = parser.parse_known_args(sys.argv[1:])
        sys.argv[:] = [sys.argv[0], *remaining]
        if OPTIONS.artifact_root is None:
            OPTIONS.artifact_root = Path(tempfile.mkdtemp(prefix=prefix))
        OPTIONS.artifact_root = OPTIONS.artifact_root.resolve()
        OPTIONS.artifact_root.mkdir(parents=True, exist_ok=True)
    return OPTIONS


def external_artifact(key):
    options = configure_test_arguments()
    if options.external_evidence_profile is None:
        raise unittest.SkipTest('Explicit --external-evidence-profile required for ' + key)
    profile_path = options.external_evidence_profile.resolve()
    profile = json.loads(profile_path.read_text(encoding='utf-8-sig'))
    if profile.get('schema') != 'chemical-skill-external-regression-profile-v1':
        raise ValueError('Unknown external evidence profile schema')
    item = profile.get('artifacts', {}).get(key)
    if item is None:
        raise unittest.SkipTest('External profile does not supply ' + key)
    path = Path(item['path'])
    path = path.resolve() if path.is_absolute() else (profile_path.parent / path).resolve()
    if item.get('evidence_class') != 'external_existing_evidence':
        raise ValueError('External evidence identity must be explicit')
    if reference(path)['sha256'] != str(item.get('sha256', '')).upper():
        raise ValueError('External evidence missing or hash drift: ' + key)
    return path


def load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def current_parser_receipt():
    """Execute checks before producing a qualified code-result receipt."""
    global RECEIPT
    if RECEIPT is not None:
        return RECEIPT
    output = configure_test_arguments().artifact_root / 'public_parser_code_validation'
    output.mkdir(parents=True, exist_ok=False)
    operations = SKILLS / 'aspen-plus-operations'
    scripts = operations / 'scripts'
    source = scripts / 'aspen_evidence.py'
    tests = scripts / 'tests/test_aspen_evidence.py'
    sys.path.insert(0, str(scripts))
    module = load_module('_portable_parser_unit_tests', tests)
    suite = unittest.defaultTestLoader.loadTestsFromModule(module)
    stream = io.StringIO()
    result = unittest.TextTestRunner(stream=stream, verbosity=2).run(suite)
    (output / 'unit_tests.txt').write_text(stream.getvalue(), encoding='utf-8')
    ev = module.ev
    probes = []
    for text in ['* WARNING', 'WARNING IN THE BLOCK X', 'WARNING WHILE CALCULATING',
                 'SEVERE ERROR IN THE BLOCK X', 'ERROR WHILE EXECUTING', 'TERMINAL ERROR',
                 'CHECK THE RUN STATUS', 'FAILED TO CONVERGE', 'ZERO FEED', 'BLOCK BYPASSED']:
        messages = ev.find_hard_messages(text)
        probes.append({'input': text, 'synthetic': True, 'messages': messages, 'passed': bool(messages)})
    formats = []
    fixture_paths = [operations / 'references/fixtures/native_summary_warning.txt',
                     operations / 'references/fixtures/native_summary_errors.txt']
    for path, expected in zip(fixture_paths, [
            [('Warnings', 'Simulation', 23)],
            [('Severe Errors', 'Simulation', 6), ('Errors', 'Simulation', 145), ('Warnings', 'Physical Property', 1)] ]):
        parsed = ev.parse_summary_counts(path.read_text(encoding='utf-8-sig'))
        cells = {(item['row'], item['column'], item['value']) for item in parsed['nonzero_cells']}
        passed = (parsed['complete'] is True and parsed['valid_schema'] is True
                  and parsed['all_zero'] is False and cells == set(expected))
        formats.append({'artifact': reference(path), 'synthetic': False,
                        'scope': 'source-preserved native summary excerpt, not a full simulation history',
                        'expected_nonzero_cells': expected, 'parsed': parsed, 'passed': passed})
    success = result.wasSuccessful() and all(x['passed'] for x in probes + formats)
    receipt = {
        'schema': 'aspen-parser-refactor-validation-v1',
        'status': 'PASS_OFFLINE_DYNAMIC_UNVERIFIED' if success else 'FAIL_OFFLINE_CODE_VALIDATION',
        'aspen_or_com_started': False,
        'scope': 'Fresh execution of packaged parser tests only; no engineering or simulation acceptance.',
        'unit_tests': {'run': result.testsRun, 'failures': len(result.failures), 'errors': len(result.errors)},
        'legacy_probes': {'count': len(probes), 'passed': sum(x['passed'] for x in probes), 'results': probes},
        'real_historical_format_fixtures': {'count': len(formats), 'passed': sum(x['passed'] for x in formats), 'results': formats},
        'files': [reference(path) for path in [source, tests, Path(__file__),
                  operations / 'references/summary_format_contract.md', *fixture_paths]],
    }
    RECEIPT = output / 'validation_report.json'
    RECEIPT.write_text(json.dumps(receipt, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    if not success:
        raise AssertionError('Packaged parser verification failed: ' + str(RECEIPT))
    return RECEIPT
