from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
STARTER_REFS = ROOT / "references"
ASSET_SCRIPTS = ROOT / "assets" / "project-skill-template"
INIT_SKILL = Path.home() / ".codex" / "skills" / ".system" / "skill-creator" / "scripts" / "init_skill.py"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def inventory_ready(inventory: Path) -> tuple[bool, list[str]]:
    reasons: list[str] = []
    assignments = read_csv(inventory / "equipment_method_assignment.csv")
    for row in assignments:
        if row.get("mapping_status") not in {"reviewed", "rule_fixed"}:
            reasons.append(f"{row['equipment_item_id']}:mapping_not_reviewed")
        if row.get("method_id") in {"", "METHOD_GAP"}:
            reasons.append(f"{row['equipment_item_id']}:method_gap")
        if "excluded" not in row.get("scope_class", "") and not row.get("source_ids", "").strip():
            reasons.append(f"{row['equipment_item_id']}:source_missing")
    requests = read_csv(inventory / "source_request_register.csv")
    for row in requests:
        if row.get("status", "").strip().lower() not in {"resolved", "closed", "not_applicable"}:
            reasons.append(f"{row.get('gap_id')}:request_open")
    return not reasons, sorted(set(reasons))


def generated_skill_md(name: str, spec: dict[str, Any]) -> str:
    project = str(spec["project_name"]).replace('"', "'")
    template = str(spec["template_id"]).replace('"', "'")
    description = (
        f'Analyze non-reactor equipment costs for the generated Aspen project {project} '
        f'and mother template {template}. Use for the fixed hierarchy mother template '
        'to contained equipment to sourced sizing/cost recipe to manifest-driven batch audit.'
    )
    audit_path = Path.home() / ".codex" / "skills" / name / "scripts" / "audit_generated_method.py"
    runner_path = Path.home() / ".codex" / "skills" / name / "scripts" / "run_recipe_batch.py"
    return f'''---
name: {name}
description: "{description}"
---

# {project} Equipment Cost

<!-- Generated by aspen-flowsheet-cost-skill-builder -->

## Scope

This Skill is specialized to mother template `{template}`. It keeps two cost
layers: nullable strict engineering candidates and an always-numeric comparison
layer. Utility OPEX remains separate. It never modifies Aspen files and never
substitutes installed cost or total capital for purchased equipment.

Always answer in this order:

```text
mother template -> equipment item -> parameters and evidence -> sizing steps
                -> cost source/basis -> candidate or unresolved status
```

## Required Workflow

1. Verify the current BKP/INP identity against `references/mother-template.csv`.
2. Read the exact row in `references/equipment-method-assignment.csv` and the
   method contract in `references/method-library.csv`.
3. Run the method audit before calculation:

```powershell
python {audit_path}
```

4. Preserve mapping, source, hash, exact-anchor, and open-request failures as
   strict-method blockers. Stop only if the comparison fallback contract fails.
5. Populate one equipment input CSV per case. Keep all units and explicit design
   factors in `parameters_json`.
6. Run the batch. It always emits numeric comparison totals and retains every
   strict unresolved state:

```powershell
python {runner_path} `
  --manifest <absolute_manifest.csv> --out-dir <absolute_output_directory>
```

Add `--strict-engineering` only when the command must fail unless every physical
item is reviewed and has a strict engineering value. The default comparison
run succeeds only when every row has central/low/high values, a rule ID, and a
source. Physical gaps are positive replacements; only documented scope rows
and letdown service may contribute structural zero.

## Hard Gates

- Absolute path plus current SHA256 is identity.
- Block type proposes a mapping; physical service and boundary approve it.
- Missing, parse-failed, rejected, and out-of-range strict values are null,
  never zero.
- Reactors and logical/bulk rows are excluded but retained in the audit.
- Interpolate only within one approved source group and its published range.
- Expose index, material, pressure, design, quantity, currency, and location
  adjustments separately.
- Emit a strict selected total only when every included physical item is
  calculated and `selected_after_review=yes`.
- Emit a comparison total for every case by applying the ordered IF rules in
  `references/comparison-cost-fallback-policy.csv`.

## References

- `references/equipment-inventory.csv`: every Aspen block and connection.
- `references/equipment-method-assignment.csv`: reviewed physical mapping.
- `references/missing-parameter-register.csv`: runtime data contract.
- `references/source-request-register.csv`: open or resolved evidence gaps.
- `references/source-evidence-ledger.csv`: source authority and provenance.
- `references/method-library.csv`: equations, units, ranges, and rejection rules.
- `references/replacement-cost-library.csv`: method and universal fallback
  anchors used only by the comparison layer.
- `references/comparison-service-replacement-library.csv`: service-matched
  comparison anchors when available.
- `references/comparison-completion-schema.md`: IF order, output fields,
  scaling, uncertainty, and audit requirements.
- `references/batch-manifest-template.csv` and
  `references/equipment-input-template.csv`: executable batch schemas.
'''


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a project-specific Aspen equipment-cost Skill.")
    parser.add_argument("--inventory-dir", type=Path, required=True)
    parser.add_argument("--data-dir", type=Path, help="User-provided, licensed and reviewed cost CSV directory; never bundled.")
    parser.add_argument("--skill-name", required=True)
    parser.add_argument("--skills-root", type=Path, default=Path.home() / ".codex" / "skills")
    parser.add_argument("--require-ready", action="store_true")
    parser.add_argument("--update", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    inventory = args.inventory_dir.resolve()
    data_dir = args.data_dir.expanduser().resolve() if args.data_dir else None
    required_data = [
        "method-library.csv", "netl-equipment-cost-points.csv",
        "replacement-cost-library.csv", "comparison-service-replacement-library.csv",
        "comparison-cost-fallback-policy.csv",
    ]
    if not (inventory / "source_evidence_ledger.csv").is_file():
        required_data.append("source-catalog.csv")
    missing_data = [name for name in required_data if data_dir is None or not (data_dir / name).is_file() or (data_dir / name).stat().st_size == 0]
    if missing_data:
        print(json.dumps({"status": "dependency_unavailable", "dependency": "reviewed_cost_csv_data",
                          "required_argument": "--data-dir", "missing_files": missing_data,
                          "outputs_created": False, "costs_calculated": False}, ensure_ascii=False, indent=2))
        return 2
    required = [
        "skill_spec.json", "mother_template_inventory.csv", "equipment_inventory.csv",
        "equipment_method_assignment.csv", "missing_parameter_register.csv",
        "source_request_register.csv",
        "source_search_log.csv",
    ]
    missing = [name for name in required if not (inventory / name).exists()]
    if missing:
        raise SystemExit(f"Inventory is incomplete: {missing}")
    name = args.skill_name.strip().lower()
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name) or len(name) > 64:
        raise SystemExit("skill-name must be lowercase hyphen-case and at most 64 characters")

    ready, reasons = inventory_ready(inventory)
    if args.require_ready and not ready:
        print(json.dumps({"status": "not_ready", "reasons": reasons}, ensure_ascii=False, indent=2))
        return 1

    skills_root = args.skills_root.resolve()
    target = skills_root / name
    if target.exists():
        marker = target / "SKILL.md"
        generated = marker.exists() and "Generated by aspen-flowsheet-cost-skill-builder" in marker.read_text(encoding="utf-8", errors="ignore")
        if not args.update:
            raise SystemExit(f"Target already exists; use --update only for a generated Skill: {target}")
        if not generated:
            raise SystemExit(f"Refusing to overwrite a non-generated Skill: {target}")
    else:
        if not INIT_SKILL.is_file():
            print(json.dumps({"status": "dependency_unavailable", "dependency": "Codex skill initializer",
                              "outputs_created": False, "costs_calculated": False}, ensure_ascii=False))
            return 2
        command = [
            sys.executable, str(INIT_SKILL), name, "--path", str(skills_root),
            "--resources", "scripts,references",
            "--interface", f"display_name={name}",
            "--interface", "short_description=按母版逐设备执行有来源审计的非反应器设备费批量分析",
            "--interface", f"default_prompt=Use ${name} to audit and batch-calculate this generated Aspen mother-template equipment-cost method.",
        ]
        completed = subprocess.run(command, check=False)
        if completed.returncode:
            return completed.returncode

    spec = json.loads((inventory / "skill_spec.json").read_text(encoding="utf-8"))
    (target / "SKILL.md").write_text(generated_skill_md(name, spec), encoding="utf-8")
    (target / "agents").mkdir(parents=True, exist_ok=True)
    (target / "agents" / "openai.yaml").write_text(
        "interface:\n"
        f'  display_name: "{spec["project_name"]} 设备费"\n'
        '  short_description: "按母版逐设备执行有来源审计的非反应器设备费批量分析"\n'
        f'  default_prompt: "Use ${name} to audit and batch-calculate this generated Aspen mother-template equipment-cost method."\n',
        encoding="utf-8",
    )

    refs = target / "references"
    scripts = target / "scripts"
    refs.mkdir(parents=True, exist_ok=True)
    scripts.mkdir(parents=True, exist_ok=True)
    copies = {
        "mother_template_inventory.csv": "mother-template.csv",
        "equipment_inventory.csv": "equipment-inventory.csv",
        "equipment_method_assignment.csv": "equipment-method-assignment.csv",
        "missing_parameter_register.csv": "missing-parameter-register.csv",
        "source_request_register.csv": "source-request-register.csv",
        "source_search_log.csv": "source-search-log.csv",
    }
    for source, destination in copies.items():
        shutil.copy2(inventory / source, refs / destination)
    source_ledger = inventory / "source_evidence_ledger.csv"
    shutil.copy2(source_ledger if source_ledger.exists() else data_dir / "source-catalog.csv", refs / "source-evidence-ledger.csv")
    shutil.copy2(data_dir / "method-library.csv", refs / "method-library.csv")
    shutil.copy2(data_dir / "netl-equipment-cost-points.csv", refs / "netl-equipment-cost-points.csv")
    for filename in (
        "replacement-cost-library.csv",
        "comparison-service-replacement-library.csv",
        "comparison-cost-fallback-policy.csv",
    ):
        shutil.copy2(data_dir / filename, refs / filename)
    shutil.copy2(STARTER_REFS / "comparison-completion-schema.md", refs / "comparison-completion-schema.md")

    for filename in (
        "audit_generated_method.py", "run_recipe_batch.py",
        "netl_equipment_cost_estimators.py", "aspen_offline_sizing.py",
        "cost_basis_adjustment.py", "comparison_cost_completion.py",
    ):
        shutil.copy2(ASSET_SCRIPTS / filename, scripts / filename)

    assignments = read_csv(inventory / "equipment_method_assignment.csv")
    input_rows = [
        {
            "equipment_item_id": row["equipment_item_id"],
            "method_id": row["method_id"],
            "parameters_json": "{}",
            "selected_after_review": "no",
            "selection_reason": "",
            "note": "Populate exact case parameters and preserve units/source lineage.",
        }
        for row in assignments
    ]
    write_csv(refs / "equipment-input-template.csv", input_rows, [
        "equipment_item_id", "method_id", "parameters_json",
        "selected_after_review", "selection_reason", "note",
    ])
    mother_rows = read_csv(inventory / "mother_template_inventory.csv")
    mother = mother_rows[0]
    manifest_rows = [{
        "case_id": f"example__{spec['template_id']}",
        "template_id": spec["template_id"],
        "chain_id": "example_chain",
        "stage": "",
        "bkp_path": mother.get("bkp_path", ""),
        "expected_bkp_sha256": mother.get("bkp_sha256", ""),
        "equipment_input_csv": str(refs / "equipment-input-template.csv"),
        "base_cost_index": "",
        "target_cost_index": "",
        "index_name": "",
        "base_period": "1998_Q1",
        "target_period": "",
        "index_source": "",
        "operating_hours_per_year": "8000",
        "enabled": "yes",
        "note": "Fill an authoritative target cost index and reviewed equipment inputs before selection.",
    }]
    write_csv(refs / "batch-manifest-template.csv", manifest_rows, list(manifest_rows[0]))

    output = {
        "status": "generated_ready" if ready else "generated_draft",
        "skill_dir": str(target),
        "inventory_ready": ready,
        "external_data_dir": str(data_dir),
        "external_data_is_project_supplied": True,
        "open_reasons": reasons,
    }
    (target / "generation_audit.json").write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(output, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
